language: objective-c
osx_image: xcode9
install:
- carthage bootstrap --platform macOS --no-use-binaries
script:
- xcrun xcodebuild -project Attabench.xcodeproj -scheme Benchmarking
- swift build
- (cd SampleBenchmark.attabench && swift build)
- (cd SortedSetBenchmark.attabench && swift build)
